server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tss_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    platform: mysql

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      file-size-threshold: 2KB

logging:
  level:
    org:
      springframework:
        security: DEBUG

